### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by dennisangemi** [ValeForce/chimica#1]
Ciao! @ValeForce @jacoportis 

Innanzitutto grazie per aver curato questi appunti. Vi faccio due considerazioni 

## C1
Solitamente ogni repo GitHub è dotato di un file `README.md` (posizionato nella root) che contiene i dettagli del progetto (appunti presi da chi? Quando? Quale prof? Quale università? È possibile contribuire al progetto? Se noto un errore che faccio? Chi contatto?)

I file `.md` sono file di testo che si scrivono molto facilmente. Un esempio è il seguente 

```
# Appunti di chimica
Questo vla bla bla bla bla 

## Compilazione 
I file pdf sono stati compilati mediante bla bla bla bla 

## Contributing 
Se vuoi contribuire al progetto puoi bla bla blabla . Hai notato un errore? Puoi segnalarlo bla bla bla 

## Authors
Questi appunti sono stati curati da bla bla bla

```

## C2
Ad ogni repo è possibile associare una descrizione facendo click sull'icona dell'ingranaggio dalla root in alto a dx

![Screenshot_20230510_120100_Chrome](https://github.com/ValeForce/chimica/assets/77018886/c66a5739-012e-4eda-8ee7-eb3ec0c71688)

Baci

**Comment by jacoportis** [comment]
Ciao @dennisangemi, ho provato ad abbozzare un readme ma essendo il primo che abbia mai fatto non sono sicuro di averlo scritto in maniera adatta. Puoi darmi un feedback?

**Comment by dennisangemi** [comment]
@jacoportis mi sembra ottimo, grazie! Aggiungerei solo:
- un riferimento a unict 
- il nome dell'estensione usata in visual studio code (perché di base è un editor di testo che non permette di compilare)

Piccolo tip:
Se vuoi, quando fai il commit puoi includere nel commit message un `#1` in modo tale da riferire quella modifica a questa issue (che è la numero 1).
